### ISSUE TITLE
Controllers don't show up in 5.6 using latest SteamVR

### ISSUE THREAD

**Issue by eobet** [JScott/ViveGrip#18]
I tried you example scene, but the controllers are invisible+non working using Unity 5.6 and the latest version of SteamVR (using a HTC Vive).

**Comment by JScott** [comment]
The controllers disappearing seems to be a common problem in 5.6: http://answers.unity3d.com/questions/1299567/vive-controllers-not-tracking-in-unity-560b3.html

I'll make some time soon to look into it and see if I can at least fix the demo scene. I was hoping that Valve would have updated the plugin by the time 5.6 officially came out :(

**Comment by JScott** [comment]
@eobet give v2.8.1 a shot: https://github.com/JScott/ViveGrip/tree/master/Releases. I fixed the demo scene and added a note to the README about fixing it for your project.

**Comment by eobet** [comment]
Brilliant, thank you very much! I can now see the hands and the interaction works great.

One small thing I noted in the example scene was that the door handle appeared a bit "floaty". It's not 100% fixed in place, but that's a minor detail and possibly a Unity physics thing.

**Comment by JScott** [comment]
Yeah, the door is a bit weird because it's quick and dirty. I remember that the local rotation and size become a factor because I'm using primitives instead of an actual model.

Feel free to make another issue for this. It'll sit on the back burner for a while but I should probably make an actual door model and improve the code at some point.
