### ISSUE TITLE
How to integrate with Valve's InteractionSystem?

### ISSUE THREAD

**Issue by eobet** [JScott/ViveGrip#19]
Valve have updated their SteamVR plugin with their own InteractionSystem which enables controller hint text, UI menu interactions, teleportation locomotion and also grabbing and throwing. However, their grabbing and throwing does not respect Unity physics like this implementation does (all of Valve's throwable objects pass through world geometry when you hold them).

If you want to take advantage of what their InteractionSystem offers, you need to use their new camera rig, and this seems to break ViveGrip.

I watched your Youtube tutorial and added the Vive Grip_Controller Handler and Vive Grip_Grip Point to the Attach_ControllerTip of both Hand1 and Hand2 in the new rig. I also added the Steam VR_Tracked Object to the hands (something no longer required in the InteractionSystem) and assigned them to the Vive Grip_Controller Handler. I then tried to move a few objects in your example scene, but nothing happened (even if I added the new interactable script to them to get Valve's highlights, etc).

Perhaps I missed a step in the above procedure or perhaps there is another source of the incompatibility. Any assistance would be greatly appreciated!

**Comment by JScott** [comment]
I don't think I have time this week to dive into it but I am very interested in getting this working. Vive Grip is modular by design to more easily support custom rigs like this. Using Vive Grip with Valve's InteractionSystem might even warrant its own tutorial once this is working.

If I had to guess, I'd say that something broke in the chain of controller handling and Tracked Objects because I don't actually directly use the SteamVR API much outside of handling controller input. In fact, the only reason I need to attach to a Tracked Object instead of just a Transform or something is because that provides me the index to get that controller input.

How does the controller work if a Tracked Object isn't required? Does it add one automatically or does it work entirely without it? Does it just not use controller input by default? I have no idea how the InteractionSystem works yet.

**Comment by JScott** [comment]
I worked with eobet over email to get this working. [v2.10](https://github.com/JScott/ViveGrip/releases/tag/v2.10.0) has all the Interaction System bits along with a few other things.
